version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: brahma_app
    working_dir: /usr/src/app
    depends_on:
      - db
    ports:
      - 3332:3332
  db:
    image: mysql
    container_name: brahma_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=creator
      - MYSQL_DATABASE=creator
      - MYSQL_USER=creator
      - MYSQL_PASSWORD=creator
